
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include_dir_list includes/automations/
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include_dir_list includes/sensors/
webostv: !include includes/webostv/webostv.yaml
spotify: !include includes/spotify/spotify.yaml

rest_command:
  plex_ready_request:
    url: http://192.168.1.44:8080/plexReady
    method: GET

google_assistant:
  project_id: home-asisstant-96f56
  service_account: !include service_account.json
  report_state: true
  exposed_domains:
    - switch
    - light
    - media_player
